# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        CommonBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        secured_area:
            logout:
                path:   /logout
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: ^/admin/user/*, roles: ROLE_ADMIN }
        #- { path: ^/admin, roles: [ROLE_ADMIN, ROLE_ADMIN] }