# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        secured_area:
            logout:
                path:   /logout
                target: /
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            provider: our_db_provider



    access_control:
        # require ROLE_ADMIN for /admin*
#        - { path: ^/admin/user/*, roles: ROLE_ADMIN }
        - { path: ^/administration, roles: ROLE_ADMIN }